### PR TITLE
Fix crash in ColorAnnotator

### PR DESCRIPTION
**Pull request by SiebelsTim**
The ColorAnnotator would crash if the right hand side is not an `KtExpression` (e.g. `KtPropertyDelegate`).

Also, I turned last arguments that are a lambda out of the parenthesis.

### CODE REVIEW

**Comment by SiebelsTim** [comment]
Also: I stepped through the entire sample base (without clicking anything). I did not encounter further crashes.

**Comment by edvin** [comment]
Sweet! I'll build another release!

**Comment by SiebelsTim** [comment]
Wow, were you waiting for a PR? :D That was fast.

**Comment by edvin** [comment]
Yes, I've been ready the whole day, just waiting for this! 😀 Hehe.. Thanks again Tim!

**Comment by nimakro** [comment]
@Tim awesome... I actually wanted to fix this a while back but forgot about
it...I am currently on vacation with very limited internet reception...I
hope to be more helpful after that again :-) ... but looks like you got
everything under control :-p

Edvin Syse <notifications@github.com> schrieb am Mi., 29. Aug. 2018, 13:42:

**Comment by edvin** [comment]
Sorry that everything is so slow going with me these days. Just trying to hang in there :) Tim, do you know how to change the version/compatibility string as well? I think that's the last piece we need before we can deploy.

**Comment by SiebelsTim** [comment]
Don't feel any obligations you guys, I sure don't :) 

I'll open a PR for the version thing right away.

**Comment by edvin** [comment]
Thank you!

**Pull request merged**
