### PR TITLE
Kotlin 1.4

### PR DESCRIPTION
**Pull request by SchweinchenFuntik**
addet support kotlin 1.4. 

the problem is found, and a little of my carelessness:
https://jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2020.html#changes-in-kotlin-plugin-14

PS: decided to recreate because I decided to delete that branch

### CODE REVIEW

**Comment by edvin** [comment]
I've invited you to become a comitter on the project, please merge at will. Also, if you build, I can upload to the JB plugin repo!

**Comment by SchweinchenFuntik** [comment]
yes I saw it, but there  need to configure the "publish Plugin", since I moved to gradle on the kotlin DSL. I'll finish today after work

**Comment by SchweinchenFuntik** [comment]
@edvin an important clarification given by the change to the kotlin plugin API is not backward compatible. Do you accept this risk?

**Comment by edvin** [comment]
Yes, with regards to how old the latest release of the plugin, and the fact that everybody has access to the latest IDEA release I feel we can/should take that risk.

**Comment by SchweinchenFuntik** [comment]
@edvin done

**Comment by SchweinchenFuntik** [comment]
@edvin created a release with an archive https://github.com/edvin/tornadofx-idea-plugin/releases/tag/1.7.20
do you need anything else to publish? This is my first time :-)

**Comment by edvin** [comment]
Thank you! I seem to have lost access to the plugin at JB, this has happened once before, trying to get it sorted now.

**Comment by edvin** [comment]
Score! Plugin update uploaded!

**Pull request merged**
