### PR TITLE
Add a quickfix for padding = Insets(10.0) -> paddingAll = 10.0

### PR DESCRIPTION
**Pull request by SiebelsTim**

### CODE REVIEW

**Comment by SiebelsTim** [comment]
I have no idea what I'm doing, so feel free to tell me what I'm doing wrong.

**Comment by edvin** [comment]
Thanks a lot! I haven't looked at the code yet, will try it during the weekend :)

**Comment by SiebelsTim** [comment]
I thought about it. The previous version would also add a warning for the following code

```
padding = Insets(++x, ++x, ++x, ++x)
```

I refactored the code a little bit, and also made sure that no complex expression (i.e. everything that is not a single expression) will be warned about. Also, it must be a reference to a variable or constant, otherwise code like the following would be warned about as well

```
        val x = { Math.random() }
        padding = Insets(x(), x(), x(), x())

```

**Review by nimakro — APPROVED** [review]
Looks good to me @SiebelsTim thanks for this PR. @edvin feel free to merge.

**Pull request merged**
